package com.knowledgehub.api.common;

public enum ErrorCode {
	VALIDATION_FAILED,
	MALFORMED_REQUEST,
	EMAIL_UNAVAILABLE,
	REGISTRATION_DISABLED,
	INVALID_CREDENTIALS,
	REFRESH_TOKEN_INVALID,
	RESET_TOKEN_INVALID,
	UPLOAD_CONFIRMATION_TOKEN_INVALID,
	ACCOUNT_DELETION_CONFIRMATION_INVALID,
	COLLECTION_NAME_UNAVAILABLE,
	UNCATEGORIZED_COLLECTION_PROTECTED,
	DOCUMENT_NOT_RETRYABLE,
	CHAT_STREAM_IN_PROGRESS,
	RATE_LIMITED,
	AUTHENTICATION_REQUIRED,
	ACCESS_DENIED,
	RESOURCE_NOT_FOUND,
	DUPLICATE_UPLOAD,
	PROCESSING_FAILED,
	LIMIT_EXCEEDED,
	PROVIDER_ERROR,
	STORAGE_ERROR,
	INTERNAL_ERROR
}
